"""Update Match model

Revision ID: 1355896276f8
Revises: a8dbdde32b3e
Create Date: 2026-07-20 17:12:06.801468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1355896276f8'
down_revision: Union[str, None] = 'a8dbdde32b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('round_number', sa.Integer(), server_default='1', nullable=False))
    op.add_column('matches', sa.Column('match_number', sa.Integer(), server_default='1', nullable=False))
    op.drop_column('matches', 'round')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('matches', 'match_number')
    op.drop_column('matches', 'round_number')
    # ### end Alembic commands ###
