"""Add description and max_players to tournaments

Revision ID: a8dbdde32b3e
Revises: 0f59e961fb48
Create Date: 2026-07-20 16:33:01.470569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8dbdde32b3e'
down_revision: Union[str, None] = '0f59e961fb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tournaments', sa.Column('max_players', sa.Integer(), server_default='16', nullable=False))
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_column('tournaments', 'max_players')
    op.drop_column('tournaments', 'description')
    # ### end Alembic commands ###
